# Generated by Django 5.1.1 on 2024-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_blog_test_blog_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
